# 3주차 데이터 분석 과제 (4장 실습)

**학번** :2276093

**이름** :김희서

**주의사항**
해당 과제를 하기 전에 파일 -> Drive에 사본 저장을 클릭하셔서 드라이브에 사본을 저장하신 후 사본에서 과제를 작성해주세요.

과제를 하시다가 어려운 점이 생기셨다면, 얼마든지 "데이터분석 분반 톡방"에 남겨주시면 멘토들이 답변 드리겠습니다.



# **0. 테스트 문제**

In [2]:
'''
1부터 16까지의 연속된 정수값을 갖는 1차원 배열을 생성하고,
2행 8열의 shape을 갖는 2차원 배열로 형태를 변환하시오.
이를 1~8, 9~16을 원소로 갖는 1차원 배열 2개를 반환하는 코드를 작성하시오.
'''
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

arr_2d = arr.reshape(2, 8)

arr1 = arr_2d[0]
arr2 = arr_2d[1]

print("첫 번째 배열:", arr1)
print("두 번째 배열:", arr2)

첫 번째 배열: [1 2 3 4 5 6 7 8]
두 번째 배열: [ 9 10 11 12 13 14 15 16]


# **1. 실습 문제**

4-2

In [1]:
# 실습4-1. 1차원 배열(list)로 numpy 배열 생성
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
# 실습4-2. 2차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# 실습4-3. 3차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
# 실습4-4. arange( ) : 정수 범위로 배열 생성
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 실습4-5. linspace() : 범위 내에서 균등 간격의 배열 생성
import numpy as np
a=np.linspace(0,10,5)
print(a)

In [8]:
# 실습4-6. logspace(): 범위 내에서 균등 간격으로 로그 스케일로 배열 생성
import numpy as np
a=np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [10]:
# 실습4-7. random : 랜덤한 수의 배열 생성
a=np.random.random()
print(a)

a=np.random.random((4,4))
print(a)

0.04452962059448595
[[0.39110059 0.1835794  0.82959612 0.31425694]
 [0.56141163 0.7731341  0.67479888 0.26453995]
 [0.2914053  0.76766972 0.52131696 0.82788255]
 [0.55947669 0.9163983  0.20962549 0.56859984]]


In [14]:
# 실습4-8. randint : 랜덤한 정수의 배열 생성
import numpy as np
a=np.random.randint(1,10)
print(a)

7


In [15]:
# 실습4-9. rand: 균등분포를 고려한 랜덤한 수의 배열 생성
import numpy as np
a=np.random.rand(3,3)
print(a)

[[0.29179912 0.28788568 0.72858579]
 [0.74387562 0.44776807 0.80112849]
 [0.51075793 0.23174468 0.90848603]]


In [16]:
# 실습4-10. randn : 표준 정규분포를 고려한 랜덤한 수의 배열 생성
import numpy as np
a=np.random.randn(3,3)
print(a)

[[-0.78775084  0.09156822 -0.99836366]
 [ 0.13133516 -1.2027743  -0.28895247]
 [-0.83257994  0.62463027 -2.07717158]]


4-3

In [17]:
# 실습4-11. 배열의 속성 알아보기
arr=np.arange(1,6)
print(arr)
print('ndimL', arr.ndim)
print('shape:',arr.shape)
print('dtype:',arr.dtype)
print('size:',arr.size)
print('itemsize:',arr.itemsize)
print('nbytes:',arr.nbytes)

[1 2 3 4 5]
ndimL 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40


In [20]:
# 실습4-12. 1차원 배열의 인덱싱 및 변경
arr=np.arange(9) #1차원 배열
print(arr)
print(arr[0])
print(arr[-1])
arr[0]=10 #요소 변경
print(arr)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [21]:
# 실습4-13. 2차원 배열의 인덱싱 및 변경
arr=np.arange(9).reshape(3,3) #2차원 배열
print(arr)
print(arr[0,1])
print(arr[1,2])
arr[0,0]=10 #요소 변경
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [22]:
# 실습4-14. 1차원 배열의 슬라이싱
arr=np.arange(6)
print(arr)
print(arr[0:3])
print(arr[1:])
print(arr[-2:])
print(arr[:-3])
print(arr[::2])
print(arr[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [23]:
# 실습4-15. 2차원 배열의 슬라이싱
arr=np.arange(1,25).reshape((4,6))
print(arr)
print(arr[1])
print(arr[1:3,1:5])
print(arr[2,:])
print(arr[:3,:3])
print(arr[2:,::-1])
print(arr[::-1,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [26]:
# 실습4-16. 불린 인덱싱 개념
arr=np.arange(1,6)
print(arr)
b=[True,False,False,True,False]
print(arr[b])

[1 2 3 4 5]
[1 4]


In [29]:
# 실습4-17. 불린 인덱싱 : 비교 연산자 사용
arr=np.arange(11)
print(arr[arr<5])

five_up=(arr>=5)
five_up
print(arr[five_up])
divide_by_2=arr[arr%2==0]
print(divide_by_2)

[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [31]:
# 실습4-18. 불리언 인덱싱 : 관계 연산자 사용
c=arr[(arr>5)&(arr<11)] #and
print(c)

d=arr[(arr>9)|(arr<5)] #or
print(d)

e=arr[~(arr%3==0)] #not
print(e)

[ 6  7  8  9 10]
[ 0  1  2  3  4 10]
[ 1  2  4  5  7  8 10]


4-4

In [33]:
# 실습 4-19. 산술 연산: 사칙연산 연산자와 함수 활용
a=np.arange(1,11)
b=np.arange(1,11)
print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [34]:
# 실습 4-20. 기타 연산: 지수, 제곱근, sin, cos, tan, log
a=np.arange(1,11)
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [36]:
# 실습 4-21. 합계: [ndarray 배열 객체].sum(), np.sum()
a=np.arange(1,10).reshape(3,3)
print(a.sum())
print(np.sum(a))
print(a)
b=a.sum(axis=0)
print(b)
c=a.sum(axis=1)
print(c)

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [37]:
# 실습 4-22. 최댓값: [ndarray 배열 객체].max(), np.max()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.max(),np.max(a))
print(a.max(axis=0),np.max(a,axis=0))
print(a.max(axis=1),np.max(a,axis=1))

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


In [38]:
# 실습 4-23. 최솟값: [ndarray 배열 객체].min(), np.min()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.min(),np.min(a))
print(a.min(axis=0),np.min(a,axis=0))
print(a.min(axis=1),np.min(a,axis=1))

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 1
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [39]:
# 실습 4-24. 평균과 중앙값: [ndarray 배열 객체].mean(), np.mean() / np.median()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.mean(),np.mean(a))
print(a.mean(axis=0),np.mean(a,axis=0))
print(a.mean(axis=1),np.mean(a,axis=1))
print(np.median(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]
5.0


In [40]:
# 실습 4-25. 표준편차: [ndarray 배열 객체].std(), np.std()
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.std(),np.std(a))
print(a.std(axis=0),np.std(a,axis=0))
print(a.std(axis=1),np.std(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


In [ ]:
# 실습 4-26. 브로드캐스팅

# 브로드캐스팅을 사용하지 않은 경우
x=np.array([1,2,3,4,5])
y=np.array([1,1,1,1,1])
print(x+y)

# 브로드캐스팅을 사용한 경우
y=1
print(x+y)

In [41]:
# 실습 4-27. shape가 다른 두 배열의 연산: 브로드캐스팅 | 스칼라 배열 변경과 연산
a=np.arange(1,25).reshape(4,6)
print(a+100) # 브로드캐스팅

new_arr=np.full_like(a,100) # 스칼라 변경
print(new_arr)
print(a+new_arr) # 배열 이항 연산

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [ ]:
# 실습 4-28. shape가 다른 두 배열의 연산: 브로드캐스팅
a=np.arange(5).reshape(1,5)
print(a)
b=np.arange(5).reshape(5,1)
print(b)
print(a+b) # 브로드캐스팅

In [42]:
# 실습 4-29. 벡터 연산 수행시간 비교
import numpy as np
import time
a=np.arange(10000000)
result=0

s=time.time()

for v in a:
  result+=v

e=time.time()
print(result,e-s) # 반복문 연산 수행 시간

s=time.time()
result=np.sum(a)
e=time.time()
print(result,e-s) # 백터 연산 수행 시간

49999995000000 1.6487419605255127
49999995000000 0.007005929946899414


4-5

In [43]:
# 실습 4-30. shape가 다른 두 배열의 연산
a=np.random.randint(1,10,(3,3))
print(a)
print(a.T) #전치 행렬

[[2 2 2]
 [7 5 4]
 [4 5 8]]
[[2 7 4]
 [2 5 5]
 [2 4 8]]


In [44]:
# 실습 4-31. 배열을 1차원 배열로 반환
a=np.array([[1,2,3],[4,5,6]])
print(a)

a.ravel()
b=a.ravel()
b[0]=10

print(b)
print(a) # b 배열 변경이 a 행렬에 반영됨

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [45]:
# 실습 4-32. reshape 함수
x=np.arange(20)
y=x.reshape(4,5)
print(y)
x[0]=10

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [48]:
# 실습 4-33. 다차원 list data를 reshape하기: np.array()

list_data=[1,2,3,4,5,6]
# list_data.reshape(3,2)
#ndarray 가 아닌 다른 자료(리스트, 튜플 등)를 바로 reshape 하면 오류 발생
# np.array() 함수를 이용해서 numpy.ndarray 로 바꾸어야 reshape 할 수 있다

data=np.array(list_data)
type(data)
print(data.reshape(3,2))
print(list_data)

[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]


In [51]:
# 실습 4-34. resize 함수: 요소 수가 동일한 경우
x=np.arange(20)
y=np.resize(x,(5,4))
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [52]:
# 실습 4-35. resize 함수: 요소 수가 더 많은 경우
x=np.arange(20)
y=np.resize(x,(5,6))
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [ ]:
# 실습 4-36. resize 함수: 요소 수가 더 적은 경우
x=np.arange(20)
y=np.resize(x,(5,3))
print(y)

In [53]:
# 실습 4-37. resize() vs reshape()
x=np.arange(20)
y=np.resize(x,(4,5))
print(y) # resize() 함수는 원래 배열과 동일한 메모리를 공유하지 않기 때문에 한 배열의 데이터 변경은 다른 배열에 매핑되지 않는다
x[0]=10
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
# 실습 4-38. 값 추가: np.append()
a=np.arange(3)
b=np.append(a,3)
print(b)

[0 1 2 3]


In [55]:
# 실습 4-39. 배열 추가
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]])
c=np.append(a,b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [56]:
# 실습 4-40. 축 추가
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]])
c=np.append(a,b,axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
# 실습 4-41. 값 추가: np.insert()
# 1차원 배열
a=np.array([1,2,3])
b=np.insert(a,1,5)
print(a)
print(b)

[1 2 3]
[1 5 2 3]


In [ ]:
# 실습 4-42. 축 추가
a=np.array([[1,1],[2,2],[3,3]])
b=np.insert(a,1,5)
print(a)
print(b)

In [59]:
# 실습 4-43. 축 추가: np.insert(arr, obj, values, axis=0) *axis=1은 세로 방향
a=np.array([[1,1],[2,2],[3,3]])
b=np.insert(a,1,5,axis=0)
c=np.insert(a,1,5,axis=1)
print(a)
print(b)
print(c)

[[1 1]
 [2 2]
 [3 3]]
[1 5 1 2 2 3 3]


In [61]:
# 실습 4-44. 값 삭제: np.delete()
a=np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]


In [62]:
# 실습 4-45. 값 삭제 축 지정
a=np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,1,axis=0))
print(np.delete(a,1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [63]:
# 실습 4-46. 배열 결합
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.concatenate((a1,a2))
print(arr)

[1 2 3 4 5 6]


In [64]:
# 실습 4-47. 배열 결합 축 지정
a1=np.array([1,2,3])
a2=np.array([4,5,6])
axis0=np.concatenate((a1,a2),axis=0)
axis1=np.concatenate((a1,a2),axis=1)
print(axis0)
print(axis1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [66]:
# 실습 4-48. 수직 방향 배열 결합: np.vstack()
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# 실습 4-49. 수평 방향 배열 결합: np.hstack()
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [68]:
# 실습 4-50. 수평 방향 배열 분리: np.hsplit()
a=np.arange(16).reshape(4,4)
a_hsplit=np.hsplit(a,2)
print(a)
print(a_hsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [70]:
# 실습 4-51. 수직 방향 배열 분리: np.vsplit()
a=np.arange(16).reshape(4,4)
a_vsplit=np.vsplit(a,2)
print(a)
print(a_vsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# **2. 연습 문제**

In [71]:
# 연습 2-1. 값이 10~50인 벡터를 만들고 벡터를 반전시켜 출력해 보세요.
import numpy as np

arr = np.arange(10, 51)
print(arr)
print('ndim:', arr.ndim)
print(arr.shape)  # 배열의 형태 출력
print(arr.dtype)  # 배열의 데이터 타입 출력
print('size:', arr.size)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
ndim: 1
(41,)
int64
size: 41


In [72]:
# 연습 2-2. 랜덤 값이 있는 10x10 배열을 만들고 최댓값과 최솟값을 찾아보세요.
import numpy as np

array = np.random.rand(10, 10)

max_value = np.max(array)
min_value = np.min(array)

print("\n최댓값:", max_value)
print("최솟값:", min_value)


최댓값: 0.9941919596210848
최솟값: 0.0016670722379912295


In [73]:
# 연습 2-3. 0~8 범위의 값을 사용하여 3x3 배열을 생성해 보세요.
import numpy as np

array = np.random.randint(0, 9, size=(3, 3))
print(array)

[[1 2 2]
 [8 7 7]
 [6 7 1]]


In [74]:
# 연습 2-4. 다음과 같이 1에서 24까지의 값을 가지는 4x6 크기의 2차원 행렬 arr을 생성해 보세요.
import numpy as np

arr = np.arange(1, 25).reshape(4, 6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [76]:
# 연습 2-5. arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요.
arr = np.arange(1, 25).reshape(4, 6)
result = arr[1:4, 1:5]
print(result)

[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]


In [91]:
# 연습 2-6. arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성해 보세요.
import numpy as np

arr = np.arange(1, 25).reshape(4, 6)
print(np.flip(arr[2:4, :]))

[[24 23 22 21 20 19]
 [18 17 16 15 14 13]]


In [79]:
# 연습 2-7. arr 배열에서 2의 배수만 출력해 보세요.
import numpy as np

arr = np.arange(1, 25)
result = arr[arr % 2 == 0]

print(result)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [80]:
# 연습 2-8. arr 배열에서 10부터 20까지의 값만 출력해 보세요.
import numpy as np

arr = np.arange(1, 25)
result = arr[(arr >= 10) & (arr <= 20)]

print(result)

[10 11 12 13 14 15 16 17 18 19 20]


In [1]:
'''
연습 4. 학생들의 근로 장학금이 numpy 배열에 저장되어 있다.
이번 학기 학생들의 근로장학금을 1.5배 올려주려고 한다.
다음은 인상된 근로 장학금을 출력하고 근로장학금이 평균 근로장학금보다 많은 학생들의 근로장학금을 출력하고 원소의 수를 출력하는 프로그램이다.
실행결과를 확인하고 빈칸에 가장 알맞은 답을 작성해 보세요.
'''

import numpy as np

scholarship = np.array([100, 200, 150, 300, 250, 400, 350])
increased_scholarship = scholarship * 1.5

print("인상된 근로 장학금:")
print(increased_scholarship)

avg_scholarship = np.mean(scholarship)

print("\n평균 근로 장학금:", avg_scholarship)

# 평균 근로 장학금보다 많은 근로 장학금을 받은 학생들의 근로 장학금
more_than_avg = scholarship[scholarship > avg_scholarship]
num_more_than_avg = len(more_than_avg)

print("\n평균 근로 장학금 이상을 받은 학생들의 근로 장학금:")
print(more_than_avg)
print("학생 수:", num_more_than_avg)

인상된 근로 장학금:
[150. 300. 225. 450. 375. 600. 525.]

평균 근로 장학금: 250.0

평균 근로 장학금 이상을 받은 학생들의 근로 장학금:
[300 400 350]
학생 수: 3
