## **4주차 데이터 분석 과제** (5단원 실습)
### **학번 :** 2276093
### **이름 :** 김희서
---
### **주의사항**
>1. 해당 과제를 하기 전에 **파일 -> Drive에 사본 저장**을 클릭하셔서 드라이브에 사본을 저장하신 후 사본에서 과제를 작성해주세요.
2. 과제를 하시다가 어려운 점이 생기셨다면, 카톡방에 질문 남겨주세요! 멘토들이 답변 드리겠습니다.
3. 예제 파일은 HoPy 구글 드라이브 폴더에서 다운 및 사용 가능합니다. 파일 사용 시, 파일명 앞에 **directory_path+**를 붙이면 다운 없이 HoPy 드라이브에서 접근하여 사용 가능합니다. -> 자세한 사용은 실습5-6 코드 셀 참고 부탁드립니다. (참고로 directory_path는 예제 파일이 있는 폴더까지의 경로를 문자열로 담은 변수!)

---



In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **0. 실습 전 할 일**

In [24]:
#구글 드라이브와 연동
from google.colab import drive
drive.mount('/content/gdrive')
directory_path = '/content/drive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장'

## HoPy 폴더를 '내 드라이브'에서 바로가기 만들어주세요!

Mounted at /content/gdrive


# **1. 실습 문제**

5-2

In [17]:
# 실습 5-1 정수형 Series 만들기
import pandas as pd
score=pd.Series([95,90,85,90,95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [ ]:
# 실습 5-2 실수형 Series 만들기
s=pd.Series([4,3.5,3.8,3,3.7])
s

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

In [ ]:
# 실습 5-3 인덱스 지정
s=pd.Series([90,80,95],index=['A','B','C'])
s

A    90
B    80
C    95
dtype: int64

In [ ]:
# 실습 5-4 넘파이로 배열 생성
import numpy as np
import pandas as pd

arr=np.arange(12).reshape(4,3)
print(arr)
print()
df=pd.DataFrame(arr)
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [ ]:
# 실습 5-5 딕셔너리로 배열 생성
import pandas as pd

df = pd.DataFrame({
    'name': ['장은실', '오경선', '양숙희'],
    'score': [90, 80, 95],
    'dept': ['com', 'eng', 'math']
})

df

name  score  dept
0  장은실     90   com
1  오경선     80   eng
2  양숙희     95  math

In [28]:
# 실습 5-6 csv 파일 불러오기
import pandas as pd
df = pd.read_csv('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/mobile.csv')
df

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [29]:
# 실습 5-6 csv 파일 불러오기 : 인덱스 지정
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/mobile.csv',index_col=0)
df

Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

5-3

In [ ]:
# 실습 5-8 csv 파일 불러오기
import pandas as pd
df=pd.read_csv('weather.csv')
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
# 실습 5-9 (행,열) 크기 확인
df.shape

(3, 3)

In [ ]:
# 실습 5-10 데이터의 전체적인 구조 출력
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   score   3 non-null      int64 
 2   dept    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [ ]:
# 실습 5-11 상위 N행 살펴보기
df.head()

date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [ ]:
# 실습 5-12 하위 N행 살펴보기
df.tail(3)

date  temp  max_wind  mean_wind
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [ ]:
# 실습 5-13 인덱스 출력
df.index

RangeIndex(start=0, stop=3653, step=1)

In [12]:
# 실습 5-14 칼럼 출력
df.columns

Index(['name', 'score', 'dept'], dtype='object')

In [ ]:
# 실습 5-15 요약 통계량 확인
df.describe()

temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

In [ ]:
# 실습 5-16 기온 칼럼의 평균 출력
df['temp'].mean()

12.942102381604162

In [30]:
# 실습 5-17 최대풍속 칼럼의 값 크기에 따라 오름차순 정렬
df.sort_values(by='max_wind')

KeyError: 'max_wind'

In [13]:
# 실습 5-18 최대풍속 칼럼의 값 크기에 따라 내림차순 정렬
df.sort_values(by='max_wind',
               ascending=False)

KeyError: 'max_wind'

In [15]:
# 실습 5-19 빈도 분석 출력
bank=pd.read_csv('bank.csv')
bank['job'].value_counts() # 내림차순
bank['job'].value_counts(ascending=True) #오름차순

FileNotFoundError: [Errno 2] No such file or directory: 'bank.csv'

In [ ]:
# 실습 5-20 column의 고유값 출력
bank['job'].unique

5-4

In [31]:
#실습 5-21 단일 컬럼 선택하기
df['temp'] # df.temp
# type(df['temp'])

KeyError: 'temp'

In [ ]:
#실습 5-22 여러 컬럼 선택하기
df[['data','temp']]

In [ ]:
#실습 5-23 여러 컬럼 선택하기: loc()
df.loc[:,['data','temp']]

In [35]:
#실습 5-24 여러 컬럼 선택하기: iloc()
df.iloc[:,[0,1]]

Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

In [32]:
#실습 5-25 특정 행 범위 선택
df[0:3]

Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150

In [1]:
#실습 5-26 특정 행 선택(레이블로 선택: df.loc[])
df.index=df['date']
df.loc['2010-08-01',['temp','mean_wind']]

NameError: name 'df' is not defined

In [ ]:
#실습 5-27 특정 행 선택(위치로 선택: df.iloc[])
df.iloc[3]

In [ ]:
#실습 5-28 특정 행과 열 선택: 슬라이싱
df.iloc[1:3,0:2]

In [ ]:
#실습 5-29 불 인덱싱: 조건에 맞는 데이터 추출
#조건: A열이 0보다 큰 데이터
w=df['temp']>=30
df[w]

In [ ]:
#실습 5-30 불 인덱싱: 조건에 맞는 데이터 추출
#조건: 최고로 더웠던 날의 모든 정보 추출
w=df['temp']==df['temp'].max
df[w]

In [ ]:
#실습 5-31 조건이 2개 이상이 녁ㅇ우 추출
#기온이 30도 이상이고 최대풍속이 9 이상인 데이터
w=(df['temp']>=30)&(df['max_wind'])>=9
df[w]

5-5

In [ ]:
#실습 5-32 결측데이터 확인
#최대풍속이 측정되지 않은 모든 데이터 출력
df[df['mean_wind'].isna()]

In [3]:
#실습 5-33 결측데이터 개수 확인: 컬럼별 결측데이터 개수 확인
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
#실습 5-34 결측데이터가 있는 행 삭제 후 확인
df2=df.dropna
df2.isnull().sum()

In [ ]:
#실습 5-35 결측데이터 대체: 평균값으로 대체
df.fillna(df.mean(),inplace=True)

In [ ]:
#실습 5-36 결측데이터 대체 후 확인
df.isnull().sum

5-6

In [38]:
#실습 5-37. 엑셀 파일 불러오기
dust=pd.read_excel('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/dust1.xlsx')

In [39]:
#실습 5-38. 컬럼 삭제
dust=dust.drop(['지역','망','측정소코드'],axis=1)
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [41]:
#실습 5-39. 컬럼 생성
dust['city']='서울'
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소  \
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  
0   서울  
1   서울  
2   서울  
3   서울  
4   서울

In [42]:
#실습 5-40. 컬럼 이름 변경
dust.rename(columns={'측정소명':'name',
                     '측정일시':'date',
                     '주소':'addr'}, inplace=True)
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='object')

In [43]:
#실습 5-41. 데이터형으로 확인
dust.dtypes

name     object
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [44]:
#실습 5-42. 숫자 int형을 문자열형으로 변환
dust['date']=dust['date'].astype(str)
dust['date']=dust['date'].str.slice(0,8)
dust.dtypes

name     object
date     object
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [45]:
#실습 5-43. 문자열형을 날짜형으로 변환
dust['date']=pd.to_datetime(dust['date'])
dust.dtypes

name            object
date    datetime64[ns]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr            object
city            object
dtype: object

In [46]:
#실습 5-44. 날짜 형식 활용 : Series.dt. 형식
dust['year']=dust['date'].dt.year
dust['month']=dust['date'].dt.month
dust['day']=dust['date'].dt.day
dust.head()

name       date    SO2   CO     O3    NO2  PM10  PM25              addr  \
0  송파구 2021-04-01  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구 2021-04-01  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구 2021-04-01  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구 2021-04-01  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구 2021-04-01  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  year  month  day  
0   서울  2021      4    1  
1   서울  2021      4    1  
2   서울  2021      4    1  
3   서울  2021      4    1  
4   서울  2021      4    1

In [48]:
#실습 5-45. 병합할 원본 데이터 확인
s1=pd.read_excel('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/nation.xlsx')
s2=pd.read_excel('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/code.xlsx')

In [49]:
#실습 5-46. 데이터 병합 : 공통 컬럼을 기준
pd.merge(s1,s2,on='국적코드')

국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

5-7

In [51]:
#실습 5-47. 한 열을 기준으로 그룹화
s1=pd.read_excel('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/nation.xlsx')
s1.groupby('국적코드').sum()

성별    입국객수    증가수
국적코드                     
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [53]:
#실습 5-48. 여러 열을 기준으로 그룹화
s1=pd.read_excel('/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/nation.xlsx')
s1.groupby(['국적코드','성별']).sum()

입국객수    증가수
국적코드 성별               
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

# **2. 연습 문제**

### 연습문제 #2
'코로나 이후 국민들의 매체 기기 이용량 변화'에 대한 정보를 가지고 있는 데이터 파일(covid.csv)을 이용하여 다음 문제를 해결해 보세요.

1. csv 파일을 불러와서 데이터를 확인해 보세요.
2. 사례수가 가장 높은 항목의 모든 정보를 출력해 보세요.
3. 증가율이 높은 3개의 항목을 출력해 보세요.

**-> p.221의 실행결과를 참고하여 코드를 작성하세요.**

-> 사용 예제 파일: covid.csv

In [72]:
# 연습 2-1 코드
import pandas as pd

df = pd.read_csv("/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/covid19.csv", encoding='cp949')
print(df.head())

most_cases = df.iloc[0]
print("사례수가 가장 높은 항목의 정보:")
print(most_cases)

# 증가율이 높은 3개 항목 출력

       연번        확진일  환자번호  국적  환자정보    지역  여행력           접촉력  조치사항 상태 이동경로  \
0  106332  2021.10.7   NaN NaN   NaN   은평구  NaN  마포구 소재 시장 관련   NaN  -  NaN   
1  106331  2021.10.7   NaN NaN   NaN  영등포구  NaN      감염경로 조사중   NaN  -  NaN   
2  106330  2021.10.7   NaN NaN   NaN   구로구  NaN      감염경로 조사중   NaN  -  NaN   
3  106329  2021.10.7   NaN NaN   NaN  동대문구  NaN      감염경로 조사중   NaN  -  NaN   
4  106328  2021.10.7   NaN NaN   NaN   성북구  NaN      감염경로 조사중   NaN  -  NaN   

               등록일              수정일 노출여부  
0  2021.10.8 10:05  2021.10.8 10:05    Y  
1  2021.10.8 10:05  2021.10.8 10:05    Y  
2  2021.10.8 10:05  2021.10.8 10:05    Y  
3  2021.10.8 10:05  2021.10.8 10:05    Y  
4  2021.10.8 10:05  2021.10.8 10:05    Y  
사례수가 가장 높은 항목의 정보:
연번               106332
확진일           2021.10.7
환자번호                NaN
국적                  NaN
환자정보                NaN
지역                  은평구
여행력                 NaN
접촉력        마포구 소재 시장 관련
조치사항                NaN
상태                    -
이동경로    

In [ ]:
# 연습 2-2 코드

In [ ]:
# 연습 2-3 코드


### 연습문제 #3
'서울특별시 코로나19 백신 예방접종 현황'에 대한 정보를 가지고 있는 데이터 파일(vaccine.csv)을 이용하여 다음 문제를 차례대로 수행하세요.

1. csv 파일을 불러와서 하위 5행의 데이터를 확인해 보세요.
2. 필요 없는 열을 삭제한 후 출력해 보세요. (삭제할 열 : day1sum, day1rate, day2sum, day2rate)
3. 데이터프레임의 기초통계량을 확인해 보세요.
4. 월별 평균을 출력해 보세요.

**-> p.222~3의 실행결과를 참고하여 코드를 작성하세요.**

-> 사용 예제 파일: vaccine.csv

In [62]:
# 연습 3-1 코드
import pandas as pd

df = pd.read_csv("/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/vaccine.csv", encoding='cp949')

print("하위 5행의 데이터:")
print(df.tail(5))

df.drop(['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1, inplace=True)

print("\n삭제 후 데이터:")
print(df)

print("\n기초 통계량:")
print(df.describe())

print("\n월별 평균:")
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
monthly_avg = df.groupby('month').mean()
print(monthly_avg)

하위 5행의 데이터:
           date  subject  day1num  day1sum  day1rate  day2num  day2sum  \
174  2021.04.25  1023346    23323   350631      34.2     3411    18513   
175  2021.04.24  1023346      200   350427      34.2        0    18513   
176  2021.04.23  1027740    10195   345764      33.6      119    18376   
177  2021.04.22  1023538    27074   317386      31.0     2479    15901   
178  2021.04.21  1019322    22501   291857      28.6     2358    13543   

     day2rate  
174       1.8  
175       1.8  
176       1.8  
177       1.6  
178       1.3  

삭제 후 데이터:
           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2

In [ ]:
# 연습 3-2 코드

In [ ]:
# 연습 3-3 코드

In [ ]:
# 연습 3-4 코드

### 연습문제 #4
수강과 교수 데이터 파일을 이용하여 다음 문제를 해결해 보세요.

1. 두 데이터프레임을 merge()함수를 사용하여 p.224와 같이 결합하고 출력해 보세요.
2. 교수 테이블에서 학과별 인원수를 출력해 보세요. (count() 함수를 사용한다.)

**-> p.224의 실행결과를 참고하여 코드를 작성하세요.**

-> 사용 예제 파일: professor.csv, signup.csv

In [71]:
# 연습 4-1 코드
import pandas as pd

professor = pd.read_csv("/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/professor.csv", encoding='cp949')
signup = pd.read_csv("/content/gdrive/MyDrive/HoPy/2024-1/데이터분석/예제 및 연습 문제_ 데이터/5장/signup.csv", encoding='cp949')
print(professor.head())
print(signup.head())

merged_data = pd.merge(signup, professor, on='담당교수', how='left')
merged_data.dropna(subset=['학과'], inplace=True)
print(merged_data)

department_counts = professor['학과'].value_counts()
print(department_counts)

  담당교수     학과
0  양숙희  컴퓨터공학
1  장은실   정보통신
2  오경선   인공지능
3  황복동  컴퓨터공학
4  정명식   인공지능
   수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능
학과
컴퓨터공학    2
인공지능     2
정보통신     1
Name: count, dtype: int64


In [ ]:
# 연습 4-2 코드